### ISSUE TITLE
How do you keep your Windows file up to date?

### ISSUE THREAD

**Issue by sailikk** [nickjj/dotfiles#8]
Hi Nick, thanks for all your setup tutorials, they have really helped out your fellow WSLer..

My question is about version control with the files you have on your C drive. How do you keep these under version control? The easiest way I can think of without installing odd things like Git for Windows would be to make a directory in the Linux partition, clone the whole repo, and just copy over the files over to your C drive (as you recommend to those forking your dotfiles in the README). Is this the way you do things? Just copy over your `settings.json` or similar files when you make a tiny change? This seems somewhat tedious haha.

This is the only thing preventing me from obtaining a foolproof setup. I would appreciate if you could detail what you are doing to keep these files up to date. Thanks.

**Comment by nickjj** [comment]
Hi,

The Windows files you see here are copied over to their respective directories in Windows when they change. It's a bit tedious but things like VcXsrv config never change. It's really only the MS Terminal config that occasionally changes (very rarely).

In the future when file access speed between drive mounts and WSL 2 improves you can use a Windows shortcut to reference the the file. Technically you can do that now I suppose. I haven't bothered because I didn't want it to affect start up times of a such as the terminal, but I'll admit I never tested it. That would be a good end game solution since it's the same as a Linux symlink. No copying required on change.

**Comment by sailikk** [comment]
Are you referring to this kind of integration: https://blogs.windows.com/windows-insider/2020/04/08/announcing-windows-10-insider-preview-build-19603/

This says that people will be able to access Linux from the File explorer, but it seems you can already do that from `\\wsl$`. Was this the one, or was there another blog or article you were referring to? Just curious.

**Comment by nickjj** [comment]
Yeah you can already access them through mounts with the stable build of WSL 2.

If you use my dotfiles you can run `cd /c` from WSL and now you can interact with your Windows files in WSL. You can also do things like run `explorer.exe .` from any directory in WSL to open Explorer and then drag it to your Explorer side bar to make quick access shortcuts.

But accessing these files from Windows inside of WSL is a bit slow. A lot slower than it was with WSL 1.

**Comment by sailikk** [comment]
Yea, hopefully Microsoft allows us to create symlinks in the Windows partition to files in the WSL partitition soon. Let me know if you know of any plans to introduce this later on by the development team. Otherwise feel free to close. Thanks.

**Comment by nickjj** [comment]
You can already create shortcuts in Windows to files in WSL. Open a WSL directory in explorer and then right click a file. You can create a shortcut.

I choose not to use them because of this from a previous reply:

> Technically you can do that now I suppose. I haven't bothered because I didn't want it to affect start up times of a such as the terminal, but I'll admit I never tested it.

**Comment by sailikk** [comment]
As a note, since you said you hadn't tried it: The shortcut method doesn't seem to be working at all. That is, I created a shortcut named settings.json (pointing to a file in the WSL partition) in the usual AppData config location for Windows Terminal. However, this just led to Windows Terminal creating a new file `settings.json` altogether disregarding the shortcut. Seems like the development team will have to work on this, if they ever want to implement it.

I only got around to trying your setup now, but what command do you use to "copy" the `settings.json` file to the appropriate location on the windows partition? Obviously you could do something like:
```
cp ~/dotfiles/c/Users/Nick/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json /mnt/c/Users/Nick/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
```
but this takes way too long to type. Do you have an alias set up somewhere to do this? I didn't see anything in your `bashrc`. I was just wondering why you preserved the very long directory structure of Windows, and instead not store it somewhere like `~/dotfiles/settings.json`, so you could do:
```
cp ~/dotfiles/settings.json /mnt/c/Users/Nick/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
```
(this is a bit shorter but not that much better still)

**Comment by nickjj** [comment]
I used the original path in the repo so it matches the path on where the file needs to go within Windows. It becomes kind of self documented that way. Otherwise we wouldn't know what `settings.json` is for at a glance.

Usually I do it the other way around. I use the Windows tool naturally while editing its config file and then when I'm happy with how things are going I eventually port it over to the dotfiles one. This only happens once in a blue moon.

I'd be curious if you could create a Linux symlink from the dotfiles repo to the Windows path. Similar to your copy command. Would Microsoft Terminal register that as a valid file?

**Comment by sailikk** [comment]
> I'd be curious if you could create a Linux symlink from the dotfiles repo to the Windows path. Similar to your copy command. Would Microsoft Terminal register that as a valid file?

Nope, Microsoft Terminal says it can't load this file.

I see what you're saying though. Edit in Windows, port it over once your happy. Still annoyed about the length of that directory structure though. Lots of clicking/typing.

**Comment by nickjj** [comment]
> Still annoyed about the length of that directory structure though. Lots of clicking/typing.

It's not too bad. The directory structure doesn't come into play.

- The MS terminal has a way to launch its settings from the menu, so you can do that to open the file.
- Then it's a quick `CTRL + A` and `CTRL + C` to copy it your config.
- From there, you pop into your dotfiles repo in Vim, `CTRL +P` and fuzzy search "setpy" to open the file.
- And now you can finish it off in Vim with `Shift + V + G` and `p` to replace the file with what's in your clipboard.

**Comment by sailikk** [comment]
Thank you for detailing how you do this! I had never realized fuzzy search can do this kind of stuff. I'm going to integrate it into my setup today!
